version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/backend
  - source: server_configs/apache2/backend.conf
    destination: /etc/apache2/sites-enabled/
    runas: ubuntu
  - source: server_configs/apache2/backend.conf
    destination: /etc/apache2/sites-available/
    runas: ubuntu

hooks:
  BeforeInstall:
      - location: server_configs/scripts/before_install.sh
  AfterInstall:
      - location: server_configs/scripts/after_install.sh