version: 0.2

env:
  variables:
    DJANGO_SECRET_KEY: "24s=ym=!@087nv8+v9_5d097=l5lt%&c48gh)auv&$ycdo(%7c"
    DEBUG_MODE: "True"
    GOOGLE_OAUTH_CLIENT_ID: "776874295259-53ophl75eqo7l0bfgad108p7nm75do1i.apps.googleusercontent.com"

phases:
  pre_build:
    commands:
      - echo "Before running tests"
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running all unit tests"
      - cd api
      - python manage.py test
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
cache:
  paths:
    - '/root/.cache/pip/**/*'
    - '/var/cache/apt/archives/**/*'
    - '/var/lib/apt/lists/**/*'
    - '/etc/apt/sources.list.d/mysql.list'
    - '/etc/apt/sources.list'